[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions" # <--- OBLIGATORIO

[functions]
  node_bundler = "esbuild" # <--- Ayuda a procesar import/export moderno

# Redirección de API (para usar /api/cybermapa en el frontend)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Redirección SPA (para que React funcione al recargar)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200